name: Pint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Pint
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install Dependencies
        run: |
          composer install
      - name: Lint
        run: |
          composer lint -- --test
